version: "3.8"

services:
  app:
    container_name: gplocation-admin
    image: gplocation-admin
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
      - ./build:/app/build
    ports:
      - 3000:3000
    stdin_open: true
